### PR TITLE
Update bar_track_color

### PR DESCRIPTION
**Pull request by yomade1**

### CODE REVIEW

**Comment by bernaferrari** [comment]
Thanks!

**Comment by yomade1** [comment]
You welcome

**Comment by yomade1** [comment]
I can see you've updated the code on github but it not been updated after
compiling in android studio.

**Comment by bernaferrari** [comment]
I need to release an update to the library. Hold on! (I believe a few
hours)

**Comment by yomade1** [comment]
Alright I will be waiting

**Comment by bernaferrari** [comment]
Now it is up! Version 0.3.3.

**Comment by yomade1** [comment]
Nice I see it. It also working fine. Good job.

Also just say u wanna update it next time some things to rectify.

1 "is_touch_disabled" not working to even when set to true.

2 adding marginTop not working also.

Will notify you if I see more things that should be fixed. Nice library and
I hope for it to be bug free.

**Pull request merged**
